package com.zybar.bar.dao;

import com.zybar.bar.model.BigData;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface BigDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_big_data
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int deleteByPrimaryKey(Integer paperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_big_data
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int insert(BigData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_big_data
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int insertSelective(BigData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_big_data
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    BigData selectByPrimaryKey(Integer paperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_big_data
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int updateByPrimaryKeySelective(BigData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_big_data
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int updateByPrimaryKey(BigData record);
}