package com.zybar.bar.dao;

import com.zybar.bar.model.InveEdu;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface InveEduMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_inve_edu
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int deleteByPrimaryKey(Integer paperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_inve_edu
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int insert(InveEdu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_inve_edu
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int insertSelective(InveEdu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_inve_edu
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    InveEdu selectByPrimaryKey(Integer paperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_inve_edu
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int updateByPrimaryKeySelective(InveEdu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_inve_edu
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int updateByPrimaryKey(InveEdu record);

    List<InveEdu> selectAll(@Param("name") String name,@Param("start") int start,@Param("limit") int limit);

    int getCount(@Param("name") String name);
}