package com.zybar.bar.dao;

import com.zybar.bar.model.Live;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface LiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_live
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    int deleteByPrimaryKey(Integer liveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_live
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    int insert(Live record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_live
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    int insertSelective(Live record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_live
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    Live selectByPrimaryKey(Integer liveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_live
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    int updateByPrimaryKeySelective(Live record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_live
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    int updateByPrimaryKey(Live record);

    List<Live> getAllLive(@Param("start") int start,@Param("limit") int limit,@Param("liveName") String liveName);

    int getCount(@Param("liveName") String liveName);
}