package com.zybar.bar.dao;

import com.zybar.bar.model.MultiQuanti;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MultiQuantiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_multi_quanti
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    int deleteByPrimaryKey(Integer multiQuantiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_multi_quanti
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    int insert(MultiQuanti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_multi_quanti
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    int insertSelective(MultiQuanti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_multi_quanti
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    MultiQuanti selectByPrimaryKey(Integer multiQuantiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_multi_quanti
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    int updateByPrimaryKeySelective(MultiQuanti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_multi_quanti
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    int updateByPrimaryKey(MultiQuanti record);

    int getCount();

    List<MultiQuanti> selectAll(@Param("category") int categoty, @Param("start") int start, @Param("limit") int limit);
}