package com.zybar.bar.dao;

import com.zybar.bar.model.Paper;

public interface PaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    int deleteByPrimaryKey(Integer paperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    int insert(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    int insertSelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    Paper selectByPrimaryKey(Integer paperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    int updateByPrimaryKeySelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    int updateByPrimaryKey(Paper record);
}