package com.zybar.bar.dao;

import com.zybar.bar.model.Plan;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plan
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int deleteByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plan
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int insert(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plan
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int insertSelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plan
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    Plan selectByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plan
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int updateByPrimaryKeySelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plan
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int updateByPrimaryKey(Plan record);
}