package com.zybar.bar.dao;

import com.zybar.bar.model.PopularRanking;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PopularRankingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_popular_ranking
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    int deleteByPrimaryKey(Integer popularRankingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_popular_ranking
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    int insert(PopularRanking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_popular_ranking
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    int insertSelective(PopularRanking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_popular_ranking
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    PopularRanking selectByPrimaryKey(Integer popularRankingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_popular_ranking
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    int updateByPrimaryKeySelective(PopularRanking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_popular_ranking
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    int updateByPrimaryKey(PopularRanking record);

    List<PopularRanking> selectAllPopularRanking(@Param("start") int start,@Param("limit") int limit);

    int getCount();
}