package com.zybar.bar.dao;

import com.zybar.bar.model.Strategy;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface StrategyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_strategy
     *
     * @mbggenerated Mon Sep 02 23:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_strategy
     *
     * @mbggenerated Mon Sep 02 23:00:43 CST 2019
     */
    int insert(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_strategy
     *
     * @mbggenerated Mon Sep 02 23:00:43 CST 2019
     */
    int insertSelective(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_strategy
     *
     * @mbggenerated Mon Sep 02 23:00:43 CST 2019
     */
    Strategy selectByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_strategy
     *
     * @mbggenerated Mon Sep 02 23:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_strategy
     *
     * @mbggenerated Mon Sep 02 23:00:43 CST 2019
     */
    int updateByPrimaryKey(Strategy record);

    List<Strategy> getAllStrategy(@Param("limit") int limit, @Param("start") int start, @Param("userId") Integer userId,@Param("selectName") Integer selectName);

    int getCount(@Param("selectName") Integer selectName, @Param("userId") Integer userId);
}