package com.zybar.bar.dao;

import com.zybar.bar.model.Strategy;

import java.util.List;

public interface StrategyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_strategy
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_strategy
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    int insert(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_strategy
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    int insertSelective(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_strategy
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    Strategy selectByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_strategy
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    int updateByPrimaryKeySelective(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_strategy
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    int updateByPrimaryKey(Strategy record);

    List<Strategy> getAllStrategy();
}