package com.zybar.bar.dao;

import com.zybar.bar.model.zyView;

public interface zyViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zy_view
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    int deleteByPrimaryKey(Integer zyViewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zy_view
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    int insert(zyView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zy_view
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    int insertSelective(zyView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zy_view
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    zyView selectByPrimaryKey(Integer zyViewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zy_view
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    int updateByPrimaryKeySelective(zyView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zy_view
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    int updateByPrimaryKey(zyView record);
}