package com.zybar.bar.dao;

import com.zybar.bar.model.ZyView;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


@Mapper
public interface ZyViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zy_view
     *
     * @mbggenerated Sat Aug 17 13:39:56 CST 2019
     */
    int deleteByPrimaryKey(Integer zyViewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zy_view
     *
     * @mbggenerated Sat Aug 17 13:39:56 CST 2019
     */
    int insert(ZyView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zy_view
     *
     * @mbggenerated Sat Aug 17 13:39:56 CST 2019
     */
    int insertSelective(ZyView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zy_view
     *
     * @mbggenerated Sat Aug 17 13:39:56 CST 2019
     */
    ZyView selectByPrimaryKey(Integer zyViewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zy_view
     *
     * @mbggenerated Sat Aug 17 13:39:56 CST 2019
     */
    int updateByPrimaryKeySelective(ZyView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zy_view
     *
     * @mbggenerated Sat Aug 17 13:39:56 CST 2019
     */
    int updateByPrimaryKey(ZyView record);

    List<ZyView> getAllZyView();
}