package com.zybar.bar.dao;

import com.zybar.bar.model.Zyvoice;

public interface ZyvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zyvoice
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    int deleteByPrimaryKey(Integer voiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zyvoice
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    int insert(Zyvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zyvoice
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    int insertSelective(Zyvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zyvoice
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    Zyvoice selectByPrimaryKey(Integer voiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zyvoice
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    int updateByPrimaryKeySelective(Zyvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zyvoice
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    int updateByPrimaryKey(Zyvoice record);
}