package com.zybar.bar.dao;

import com.zybar.bar.model.Zyvoice;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;


@Mapper
public interface ZyvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zyvoice
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int deleteByPrimaryKey(Integer voiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zyvoice
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int insert(Zyvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zyvoice
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int insertSelective(Zyvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zyvoice
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    Zyvoice selectByPrimaryKey(Integer voiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zyvoice
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int updateByPrimaryKeySelective(Zyvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_zyvoice
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    int updateByPrimaryKey(Zyvoice record);

    int getCount(@Param("mp3Name") String mp3Name);

    List<Zyvoice> getAllZyVoice(@Param("mp3Name") String mp3Name,@Param("start") int start,@Param("limit") int limit);
}