package com.zybar.bar.model;

public class App {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app.app_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app.photo_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app.name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app.app_id
     *
     * @return the value of tb_app.app_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app.app_id
     *
     * @param appId the value for tb_app.app_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app.photo_url
     *
     * @return the value of tb_app.photo_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app.photo_url
     *
     * @param photoUrl the value for tb_app.photo_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app.name
     *
     * @return the value of tb_app.name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app.name
     *
     * @param name the value for tb_app.name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}