package com.zybar.bar.model;

public class BigData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_big_data.big_data_id
     *
     * @mbggenerated Tue Aug 27 03:11:10 CST 2019
     */
    private Integer bigDataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_big_data.name
     *
     * @mbggenerated Tue Aug 27 03:11:10 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_big_data.content
     *
     * @mbggenerated Tue Aug 27 03:11:10 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_big_data.update_time
     *
     * @mbggenerated Tue Aug 27 03:11:10 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_big_data.big_data_id
     *
     * @return the value of tb_big_data.big_data_id
     *
     * @mbggenerated Tue Aug 27 03:11:10 CST 2019
     */
    public Integer getBigDataId() {
        return bigDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_big_data.big_data_id
     *
     * @param bigDataId the value for tb_big_data.big_data_id
     *
     * @mbggenerated Tue Aug 27 03:11:10 CST 2019
     */
    public void setBigDataId(Integer bigDataId) {
        this.bigDataId = bigDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_big_data.name
     *
     * @return the value of tb_big_data.name
     *
     * @mbggenerated Tue Aug 27 03:11:10 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_big_data.name
     *
     * @param name the value for tb_big_data.name
     *
     * @mbggenerated Tue Aug 27 03:11:10 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_big_data.content
     *
     * @return the value of tb_big_data.content
     *
     * @mbggenerated Tue Aug 27 03:11:10 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_big_data.content
     *
     * @param content the value for tb_big_data.content
     *
     * @mbggenerated Tue Aug 27 03:11:10 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_big_data.update_time
     *
     * @return the value of tb_big_data.update_time
     *
     * @mbggenerated Tue Aug 27 03:11:10 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_big_data.update_time
     *
     * @param updateTime the value for tb_big_data.update_time
     *
     * @mbggenerated Tue Aug 27 03:11:10 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}