package com.zybar.bar.model;

public class Caopan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_caopan.paper_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_caopan.pdf_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String pdfUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_caopan.update_time
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_caopan.name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_caopan.paper_id
     *
     * @return the value of tb_caopan.paper_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_caopan.paper_id
     *
     * @param paperId the value for tb_caopan.paper_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_caopan.pdf_url
     *
     * @return the value of tb_caopan.pdf_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getPdfUrl() {
        return pdfUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_caopan.pdf_url
     *
     * @param pdfUrl the value for tb_caopan.pdf_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setPdfUrl(String pdfUrl) {
        this.pdfUrl = pdfUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_caopan.update_time
     *
     * @return the value of tb_caopan.update_time
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_caopan.update_time
     *
     * @param updateTime the value for tb_caopan.update_time
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_caopan.name
     *
     * @return the value of tb_caopan.name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_caopan.name
     *
     * @param name the value for tb_caopan.name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}