package com.zybar.bar.model;

public class InveEdu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_inve_edu.paper_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_inve_edu.name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_inve_edu.pdf_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String pdfUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_inve_edu.select_name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private Integer selectName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_inve_edu.paper_id
     *
     * @return the value of tb_inve_edu.paper_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_inve_edu.paper_id
     *
     * @param paperId the value for tb_inve_edu.paper_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_inve_edu.name
     *
     * @return the value of tb_inve_edu.name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_inve_edu.name
     *
     * @param name the value for tb_inve_edu.name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_inve_edu.pdf_url
     *
     * @return the value of tb_inve_edu.pdf_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getPdfUrl() {
        return pdfUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_inve_edu.pdf_url
     *
     * @param pdfUrl the value for tb_inve_edu.pdf_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setPdfUrl(String pdfUrl) {
        this.pdfUrl = pdfUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_inve_edu.select_name
     *
     * @return the value of tb_inve_edu.select_name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public Integer getSelectName() {
        return selectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_inve_edu.select_name
     *
     * @param selectName the value for tb_inve_edu.select_name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setSelectName(Integer selectName) {
        this.selectName = selectName;
    }
}