package com.zybar.bar.model;

public class Jianerhuo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jianerhuo.j_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private Integer jId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jianerhuo.photo_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jianerhuo.name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jianerhuo.user_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jianerhuo.update_time
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jianerhuo.j_id
     *
     * @return the value of tb_jianerhuo.j_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public Integer getjId() {
        return jId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jianerhuo.j_id
     *
     * @param jId the value for tb_jianerhuo.j_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setjId(Integer jId) {
        this.jId = jId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jianerhuo.photo_url
     *
     * @return the value of tb_jianerhuo.photo_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jianerhuo.photo_url
     *
     * @param photoUrl the value for tb_jianerhuo.photo_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jianerhuo.name
     *
     * @return the value of tb_jianerhuo.name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jianerhuo.name
     *
     * @param name the value for tb_jianerhuo.name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jianerhuo.user_id
     *
     * @return the value of tb_jianerhuo.user_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jianerhuo.user_id
     *
     * @param userId the value for tb_jianerhuo.user_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jianerhuo.update_time
     *
     * @return the value of tb_jianerhuo.update_time
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jianerhuo.update_time
     *
     * @param updateTime the value for tb_jianerhuo.update_time
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}