package com.zybar.bar.model;

public class Live {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_live.live_id
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    private Integer liveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_live.live_img_url
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    private String liveImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_live.live_url
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    private String liveUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_live.live_name
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    private String liveName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_live.live_id
     *
     * @return the value of tb_live.live_id
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    public Integer getLiveId() {
        return liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_live.live_id
     *
     * @param liveId the value for tb_live.live_id
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    public void setLiveId(Integer liveId) {
        this.liveId = liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_live.live_img_url
     *
     * @return the value of tb_live.live_img_url
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    public String getLiveImgUrl() {
        return liveImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_live.live_img_url
     *
     * @param liveImgUrl the value for tb_live.live_img_url
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    public void setLiveImgUrl(String liveImgUrl) {
        this.liveImgUrl = liveImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_live.live_url
     *
     * @return the value of tb_live.live_url
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    public String getLiveUrl() {
        return liveUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_live.live_url
     *
     * @param liveUrl the value for tb_live.live_url
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    public void setLiveUrl(String liveUrl) {
        this.liveUrl = liveUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_live.live_name
     *
     * @return the value of tb_live.live_name
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    public String getLiveName() {
        return liveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_live.live_name
     *
     * @param liveName the value for tb_live.live_name
     *
     * @mbggenerated Fri Sep 06 01:55:07 CST 2019
     */
    public void setLiveName(String liveName) {
        this.liveName = liveName;
    }
}