package com.zybar.bar.model;

public class MultiQuanti {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_multi_quanti.multi_quanti_id
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    private Integer multiQuantiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_multi_quanti.time
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_multi_quanti.variety
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    private String variety;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_multi_quanti.direction
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    private String direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_multi_quanti.point
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    private String point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_multi_quanti.category
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    private Integer category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_multi_quanti.multi_quanti_id
     *
     * @return the value of tb_multi_quanti.multi_quanti_id
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    public Integer getMultiQuantiId() {
        return multiQuantiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_multi_quanti.multi_quanti_id
     *
     * @param multiQuantiId the value for tb_multi_quanti.multi_quanti_id
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    public void setMultiQuantiId(Integer multiQuantiId) {
        this.multiQuantiId = multiQuantiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_multi_quanti.time
     *
     * @return the value of tb_multi_quanti.time
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_multi_quanti.time
     *
     * @param time the value for tb_multi_quanti.time
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_multi_quanti.variety
     *
     * @return the value of tb_multi_quanti.variety
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    public String getVariety() {
        return variety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_multi_quanti.variety
     *
     * @param variety the value for tb_multi_quanti.variety
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    public void setVariety(String variety) {
        this.variety = variety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_multi_quanti.direction
     *
     * @return the value of tb_multi_quanti.direction
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_multi_quanti.direction
     *
     * @param direction the value for tb_multi_quanti.direction
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    public void setDirection(String direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_multi_quanti.point
     *
     * @return the value of tb_multi_quanti.point
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    public String getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_multi_quanti.point
     *
     * @param point the value for tb_multi_quanti.point
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    public void setPoint(String point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_multi_quanti.category
     *
     * @return the value of tb_multi_quanti.category
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_multi_quanti.category
     *
     * @param category the value for tb_multi_quanti.category
     *
     * @mbggenerated Sat Aug 24 21:23:48 CST 2019
     */
    public void setCategory(Integer category) {
        this.category = category;
    }
}