package com.zybar.bar.model;

public class MutiQuanti {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_muti_quanti.muti_id
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    private Integer mutiId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_muti_quanti.muti_id
     *
     * @return the value of tb_muti_quanti.muti_id
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public Integer getMutiId() {
        return mutiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_muti_quanti.muti_id
     *
     * @param mutiId the value for tb_muti_quanti.muti_id
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public void setMutiId(Integer mutiId) {
        this.mutiId = mutiId;
    }
}