package com.zybar.bar.model;

import java.util.Date;

public class Paper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paper.paper_id
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paper.pdf_url
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    private String pdfUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paper.paper_name
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    private String paperName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paper.update_time
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paper.paper_id
     *
     * @return the value of tb_paper.paper_id
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paper.paper_id
     *
     * @param paperId the value for tb_paper.paper_id
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paper.pdf_url
     *
     * @return the value of tb_paper.pdf_url
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public String getPdfUrl() {
        return pdfUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paper.pdf_url
     *
     * @param pdfUrl the value for tb_paper.pdf_url
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public void setPdfUrl(String pdfUrl) {
        this.pdfUrl = pdfUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paper.paper_name
     *
     * @return the value of tb_paper.paper_name
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public String getPaperName() {
        return paperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paper.paper_name
     *
     * @param paperName the value for tb_paper.paper_name
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public void setPaperName(String paperName) {
        this.paperName = paperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paper.update_time
     *
     * @return the value of tb_paper.update_time
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paper.update_time
     *
     * @param updateTime the value for tb_paper.update_time
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}