package com.zybar.bar.model;

import java.util.Date;

public class Plan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plan.plan_id
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    private Integer planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plan.name
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plan.user_id
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plan.update_time
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plan.content
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plan.plan_id
     *
     * @return the value of tb_plan.plan_id
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plan.plan_id
     *
     * @param planId the value for tb_plan.plan_id
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plan.name
     *
     * @return the value of tb_plan.name
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plan.name
     *
     * @param name the value for tb_plan.name
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plan.user_id
     *
     * @return the value of tb_plan.user_id
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plan.user_id
     *
     * @param userId the value for tb_plan.user_id
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plan.update_time
     *
     * @return the value of tb_plan.update_time
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plan.update_time
     *
     * @param updateTime the value for tb_plan.update_time
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plan.content
     *
     * @return the value of tb_plan.content
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plan.content
     *
     * @param content the value for tb_plan.content
     *
     * @mbggenerated Thu Aug 08 10:12:12 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}