package com.zybar.bar.model;

public class PopularRanking {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_popular_ranking.popular_ranking_id
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    private Integer popularRankingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_popular_ranking.popular_ranking_num
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    private Integer popularRankingNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_popular_ranking.popular_ranking_name
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    private String popularRankingName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_popular_ranking.popular_ranking_id
     *
     * @return the value of tb_popular_ranking.popular_ranking_id
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    public Integer getPopularRankingId() {
        return popularRankingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_popular_ranking.popular_ranking_id
     *
     * @param popularRankingId the value for tb_popular_ranking.popular_ranking_id
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    public void setPopularRankingId(Integer popularRankingId) {
        this.popularRankingId = popularRankingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_popular_ranking.popular_ranking_num
     *
     * @return the value of tb_popular_ranking.popular_ranking_num
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    public Integer getPopularRankingNum() {
        return popularRankingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_popular_ranking.popular_ranking_num
     *
     * @param popularRankingNum the value for tb_popular_ranking.popular_ranking_num
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    public void setPopularRankingNum(Integer popularRankingNum) {
        this.popularRankingNum = popularRankingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_popular_ranking.popular_ranking_name
     *
     * @return the value of tb_popular_ranking.popular_ranking_name
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    public String getPopularRankingName() {
        return popularRankingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_popular_ranking.popular_ranking_name
     *
     * @param popularRankingName the value for tb_popular_ranking.popular_ranking_name
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    public void setPopularRankingName(String popularRankingName) {
        this.popularRankingName = popularRankingName;
    }
}