package com.zybar.bar.model;

public class Strategy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_strategy.s_id
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_strategy.user_id
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_strategy.stock_name
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_strategy.update_time
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_strategy.point
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    private Double point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_strategy.target
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    private Double target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_strategy.stop_loss
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    private Double stopLoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_strategy.source
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_strategy.operating
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    private String operating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_strategy.s_id
     *
     * @return the value of tb_strategy.s_id
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_strategy.s_id
     *
     * @param sId the value for tb_strategy.s_id
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_strategy.user_id
     *
     * @return the value of tb_strategy.user_id
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_strategy.user_id
     *
     * @param userId the value for tb_strategy.user_id
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_strategy.stock_name
     *
     * @return the value of tb_strategy.stock_name
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_strategy.stock_name
     *
     * @param stockName the value for tb_strategy.stock_name
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_strategy.update_time
     *
     * @return the value of tb_strategy.update_time
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_strategy.update_time
     *
     * @param updateTime the value for tb_strategy.update_time
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_strategy.point
     *
     * @return the value of tb_strategy.point
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public Double getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_strategy.point
     *
     * @param point the value for tb_strategy.point
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public void setPoint(Double point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_strategy.target
     *
     * @return the value of tb_strategy.target
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public Double getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_strategy.target
     *
     * @param target the value for tb_strategy.target
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public void setTarget(Double target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_strategy.stop_loss
     *
     * @return the value of tb_strategy.stop_loss
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public Double getStopLoss() {
        return stopLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_strategy.stop_loss
     *
     * @param stopLoss the value for tb_strategy.stop_loss
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public void setStopLoss(Double stopLoss) {
        this.stopLoss = stopLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_strategy.source
     *
     * @return the value of tb_strategy.source
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_strategy.source
     *
     * @param source the value for tb_strategy.source
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_strategy.operating
     *
     * @return the value of tb_strategy.operating
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public String getOperating() {
        return operating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_strategy.operating
     *
     * @param operating the value for tb_strategy.operating
     *
     * @mbggenerated Sat Aug 17 14:41:25 CST 2019
     */
    public void setOperating(String operating) {
        this.operating = operating;
    }
}