package com.zybar.bar.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_id
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.username
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.phone
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.role
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.photo_url
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_id
     *
     * @return the value of tb_user.user_id
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    private Integer level;
    private Integer ifHj;
    private Integer ifJj;
    private Integer ifFw;

    private String loginName;

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getIfHj() {
        return ifHj;
    }

    public void setIfHj(Integer ifHj) {
        this.ifHj = ifHj;
    }

    public Integer getIfJj() {
        return ifJj;
    }

    public void setIfJj(Integer ifJj) {
        this.ifJj = ifJj;
    }

    public Integer getIfFw() {
        return ifFw;
    }

    public void setIfFw(Integer ifFw) {
        this.ifFw = ifFw;
    }

    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_id
     *
     * @param userId the value for tb_user.user_id
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.username
     *
     * @return the value of tb_user.username
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.username
     *
     * @param username the value for tb_user.username
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.phone
     *
     * @return the value of tb_user.phone
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.phone
     *
     * @param phone the value for tb_user.phone
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.role
     *
     * @return the value of tb_user.role
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.role
     *
     * @param role the value for tb_user.role
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.photo_url
     *
     * @return the value of tb_user.photo_url
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.photo_url
     *
     * @param photoUrl the value for tb_user.photo_url
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbggenerated Sat Aug 17 13:57:43 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }
}