package com.zybar.bar.model;

public class WinningRateRanking {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_winning_rate_ranking.winning_rate_ranking_id
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    private Integer winningRateRankingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_winning_rate_ranking.winning_rate_ranking_name
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    private String winningRateRankingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_winning_rate_ranking.winning_rate_ranking_rate
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    private Float winningRateRankingRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_winning_rate_ranking.winning_rate_ranking_id
     *
     * @return the value of tb_winning_rate_ranking.winning_rate_ranking_id
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    public Integer getWinningRateRankingId() {
        return winningRateRankingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_winning_rate_ranking.winning_rate_ranking_id
     *
     * @param winningRateRankingId the value for tb_winning_rate_ranking.winning_rate_ranking_id
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    public void setWinningRateRankingId(Integer winningRateRankingId) {
        this.winningRateRankingId = winningRateRankingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_winning_rate_ranking.winning_rate_ranking_name
     *
     * @return the value of tb_winning_rate_ranking.winning_rate_ranking_name
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    public String getWinningRateRankingName() {
        return winningRateRankingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_winning_rate_ranking.winning_rate_ranking_name
     *
     * @param winningRateRankingName the value for tb_winning_rate_ranking.winning_rate_ranking_name
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    public void setWinningRateRankingName(String winningRateRankingName) {
        this.winningRateRankingName = winningRateRankingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_winning_rate_ranking.winning_rate_ranking_rate
     *
     * @return the value of tb_winning_rate_ranking.winning_rate_ranking_rate
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    public Float getWinningRateRankingRate() {
        return winningRateRankingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_winning_rate_ranking.winning_rate_ranking_rate
     *
     * @param winningRateRankingRate the value for tb_winning_rate_ranking.winning_rate_ranking_rate
     *
     * @mbggenerated Sat Aug 17 15:06:34 CST 2019
     */
    public void setWinningRateRankingRate(Float winningRateRankingRate) {
        this.winningRateRankingRate = winningRateRankingRate;
    }
}