package com.zybar.bar.model;

public class zyView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zy_view.zy_view_id
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    private Integer zyViewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zy_view.zy_view_url
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    private String zyViewUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zy_view.zy_view_creat_tiome
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    private String zyViewCreatTiome;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zy_view.zy_view_id
     *
     * @return the value of tb_zy_view.zy_view_id
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    public Integer getZyViewId() {
        return zyViewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zy_view.zy_view_id
     *
     * @param zyViewId the value for tb_zy_view.zy_view_id
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    public void setZyViewId(Integer zyViewId) {
        this.zyViewId = zyViewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zy_view.zy_view_url
     *
     * @return the value of tb_zy_view.zy_view_url
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    public String getZyViewUrl() {
        return zyViewUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zy_view.zy_view_url
     *
     * @param zyViewUrl the value for tb_zy_view.zy_view_url
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    public void setZyViewUrl(String zyViewUrl) {
        this.zyViewUrl = zyViewUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zy_view.zy_view_creat_tiome
     *
     * @return the value of tb_zy_view.zy_view_creat_tiome
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    public String getZyViewCreatTiome() {
        return zyViewCreatTiome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zy_view.zy_view_creat_tiome
     *
     * @param zyViewCreatTiome the value for tb_zy_view.zy_view_creat_tiome
     *
     * @mbggenerated Fri Aug 16 17:25:19 CST 2019
     */
    public void setZyViewCreatTiome(String zyViewCreatTiome) {
        this.zyViewCreatTiome = zyViewCreatTiome;
    }
}