package com.zybar.bar.model;

public class Zyvoice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zyvoice.voice_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private Integer voiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zyvoice.mp3_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String mp3Url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zyvoice.photo_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zyvoice.mp3_name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private String mp3Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_zyvoice.user_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zyvoice.voice_id
     *
     * @return the value of tb_zyvoice.voice_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public Integer getVoiceId() {
        return voiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zyvoice.voice_id
     *
     * @param voiceId the value for tb_zyvoice.voice_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setVoiceId(Integer voiceId) {
        this.voiceId = voiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zyvoice.mp3_url
     *
     * @return the value of tb_zyvoice.mp3_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getMp3Url() {
        return mp3Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zyvoice.mp3_url
     *
     * @param mp3Url the value for tb_zyvoice.mp3_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setMp3Url(String mp3Url) {
        this.mp3Url = mp3Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zyvoice.photo_url
     *
     * @return the value of tb_zyvoice.photo_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zyvoice.photo_url
     *
     * @param photoUrl the value for tb_zyvoice.photo_url
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zyvoice.mp3_name
     *
     * @return the value of tb_zyvoice.mp3_name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public String getMp3Name() {
        return mp3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zyvoice.mp3_name
     *
     * @param mp3Name the value for tb_zyvoice.mp3_name
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setMp3Name(String mp3Name) {
        this.mp3Name = mp3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_zyvoice.user_id
     *
     * @return the value of tb_zyvoice.user_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_zyvoice.user_id
     *
     * @param userId the value for tb_zyvoice.user_id
     *
     * @mbggenerated Thu Aug 08 17:28:24 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}